service: event-sphere-api

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  stage: dev
  versionFunctions: true
  environment:
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    STRIPE_WEBHOOK_SECRET: ${env:STRIPE_WEBHOOK_SECRET}
    FIREBASE_PROJECT_ID: ${env:FIREBASE_PROJECT_ID}
    FIREBASE_CLIENT_EMAIL: ${env:FIREBASE_CLIENT_EMAIL}
    FIREBASE_PRIVATE_KEY: ${env:FIREBASE_PRIVATE_KEY}

functions:
  stripeWebhook:
    handler: handler.stripeWebhook
    events:
      - http:
          path: api/webhook
          method: post
          cors: true

  createNotification:
    handler: handler.createNotification
    events:
      - http:
          path: notifications
          method: post
          cors: true

custom:
  build:
    esbuild: true